# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  command:
    description: 'the command to run'
    required: true
runs:
  using: 'docker'
  image: 'docker://mcr.microsoft.com/iotedge/iotedgedev:latest'
  args: 
    - 'sudo'
    - 'sh'
    - '-c' 
    - '/github/workspace/devops/entrypoint.sh'
