# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  command:
    description: 'the command to run'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.command }}
