<Project>
    <PropertyGroup>
      <EnableNETAnalyzers>true</EnableNETAnalyzers>
      <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <NoWarn>$(NoWarn);CS1591;CA1873;CA1859;CA1823;CA1515;CA2000;IDE0010;ASPDEPR008;CS1573;CS1574;CS1587;CS0419;CS1572;CA1865;CA1849;CS8633;IDE0300;CA1860;CA1001;CA1851;CA1861;CA2025;CA2213;CA2249;CS1570;CS8602;CS8620;CS8625;IDE0051;IDE0062;IDE0290;SYSLIB0051;SYSLIB0057;xUnit1044;xUnit1045</NoWarn>
      <AnalysisMode>AllEnabledByDefault</AnalysisMode>
      <AnalysisLevel>10.0</AnalysisLevel>
      <LangVersion>13.0</LangVersion>
      <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <PropertyGroup>
      <AzureStorageBlobVersion>12.14.1</AzureStorageBlobVersion>
      <DockerDotNetX509Version>3.125.12</DockerDotNetX509Version>
      <MicrosoftAzureDevicesVersion>1.38.1</MicrosoftAzureDevicesVersion>
      <MicrosoftAzureDevicesClientVersion>1.41.2</MicrosoftAzureDevicesClientVersion>
      <MicrosoftExtensionsCachingMemoryVersion>9.0.0</MicrosoftExtensionsCachingMemoryVersion>
      <MicrosoftAzureFunctionsExtensionsVersion>1.1.0</MicrosoftAzureFunctionsExtensionsVersion>
      <MicrosoftExtensionsDependencyInjectionVersion>6.0.1</MicrosoftExtensionsDependencyInjectionVersion>
      <MicrosoftExtensionsDependencyInjectionAbstractionsVersion>9.0.0</MicrosoftExtensionsDependencyInjectionAbstractionsVersion>
      <MicrosoftExtensionsPrimitivesVersion>6.0.0</MicrosoftExtensionsPrimitivesVersion>
      <MicrosoftNETSdkFunctionsVersion>4.1.3</MicrosoftNETSdkFunctionsVersion>
      <NewtonsoftJsonVersion>13.0.2</NewtonsoftJsonVersion>
      <PortableBouncyCastleVersion>1.9.0</PortableBouncyCastleVersion>
      <SystemDynamicRuntimeVersion>4.3.0</SystemDynamicRuntimeVersion>
      <StackExchangeRedisVersion>2.6.70</StackExchangeRedisVersion>
      <MicrosoftCSharpVersion>4.7.0</MicrosoftCSharpVersion>
      <ApplicationInsightsVersion>2.21.0</ApplicationInsightsVersion>
      <PrometheusNetVersion>7.0.0</PrometheusNetVersion>
      <AzureIdentityVersion>1.17.1</AzureIdentityVersion>
      <MicrosoftRestClientRuntimeVersion>2.3.24</MicrosoftRestClientRuntimeVersion>
      <SystemDrawingCommonVersion>9.0.0</SystemDrawingCommonVersion>
      <MicrosoftAspNetCoreHttpAbstractionsVersion>2.2.0</MicrosoftAspNetCoreHttpAbstractionsVersion>
      <JacobVersion>0.6.0</JacobVersion>
    </PropertyGroup>
    <PropertyGroup> <!-- this group is meant for packages required from test projects -->
      <DockerDotnetVersion>3.125.12</DockerDotnetVersion>
      <MicrosoftNETTestSdkVersion>17.11.1</MicrosoftNETTestSdkVersion>
      <MoqVersion>4.18.4</MoqVersion>
      <XUnitVersion>2.9.3</XUnitVersion>
      <XunitCombinatorialVersion>1.5.25</XunitCombinatorialVersion>
      <MicrosoftExtensionsConfigurationVersion>6.0.1</MicrosoftExtensionsConfigurationVersion>
      <MicrosoftExtensionsConfigurationBinderVersion>6.0.0</MicrosoftExtensionsConfigurationBinderVersion>
      <MicrosoftExtensionsConfigurationEnvironmentVariablesVersion>6.0.1</MicrosoftExtensionsConfigurationEnvironmentVariablesVersion>
      <MicrosoftExtensionsConfigurationJsonVersion>6.0.0</MicrosoftExtensionsConfigurationJsonVersion>
      <SystemIOPortsVersion>6.0.0</SystemIOPortsVersion>
      <XUnitRunnerVisualStudio>2.8.2</XUnitRunnerVisualStudio>
      <CoverletMSBuild>3.2.0</CoverletMSBuild>
      <MicrosoftExtensionsLogging>6.0.0</MicrosoftExtensionsLogging>
      <MicrosoftExtensionsLoggingConfiguration>6.0.0</MicrosoftExtensionsLoggingConfiguration>
      <BogusVersion>34.0.2</BogusVersion>
      <NullablePkg>1.3.0</NullablePkg>
      <MicrosoftAspNetCoreMvcTestingVersion>6.0.13</MicrosoftAspNetCoreMvcTestingVersion>
      <AzureMessagingEventHubsVersion>5.7.3</AzureMessagingEventHubsVersion>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="$(MSBuildThisFileDirectory)/AssemblyInfo.cs"
                 Condition="Exists('$(MSBuildThisFileDirectory)/AssemblyInfo.cs')"
                 Link="AssemblyInfo.cs" />
    </ItemGroup>
</Project>
