on: # rebuild any PRs and main branch changes
  repository_dispatch:
    types: manual_trigger

jobs:
  build_and_test:
    name: Build and Test Solution
    runs-on: ubuntu-16.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: echo ${{ tojson(github.event)}}